FROM confluentinc/cp-kafka-connect:7.6.0

USER root

RUN mkdir -p /usr/share/confluent-hub-components/debezium-connector-postgresql

RUN curl -L -o postgres.tar.gz https://repo1.maven.org/maven2/io/debezium/debezium-connector-postgres/2.6.1.Final/debezium-connector-postgres-2.6.1.Final-plugin.tar.gz

RUN tar -xzf postgres.tar.gz -C /usr/share/confluent-hub-components/debezium-connector-postgresql --strip-components=1

RUN rm postgres.tar.gz

USER appuser