server:
  port: 8080

spring:
  application:
    name: broker-core
  datasource:
    url: jdbc:postgresql://localhost:5433/broker_core_db
    username: broker_user
    password: broker_pass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 0.05